name: Publish

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - 'LICENSE'


jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.18'

    - name: Install dependencies
      run: go get .

    - name: Run tests
      run: go test .
    - id: get-version
      name: Compute next version based on previous tag in commit history
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        noVersionBumpBehavior: patch

    - name: Create github tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.get-version.outputs.next }}",
            sha: context.sha
          })

