name: Test

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.18'

    - name: Install dependencies
      run: go get .

    - name: Run tests
      run: go test .

